FROM golang:1.15-alpine3.12 AS multistage

RUN apk add --no-cache --update git

WORKDIR /go/src/api
COPY . .

RUN go get -d -v \
  && go install -v \
  && go build

##

FROM alpine:3.12
COPY --from=multistage /go/bin/api /go/bin/
EXPOSE 8080
CMD ["/services/bin/api"]
